spring:
  application:
    name: flux
  r2dbc:
    url: r2dbc:mysql://localhost:3306/flux
    username: root
    password: 1234
  webflux:
    base-path: /api

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG